### ISSUE TITLE
Latest Gnome Version Not Available to Download

### ISSUE THREAD

**Issue by lfom** [CachyOS/CachyOS-Live-ISO#7]
Hello, there!

First, congrats on the project. I really like the idea of an easy-to-install Arch-based distro that includes optimizations for newest hardware.

I was hoping to install the latest Gnome version of the GUI installer (220624 as of now), but only the KDE version is available from sourceforge.net. Then I found the ISO in aur.cachyos.org (it is the same server as mirror.cachyos.org, right?), but the download always fails after a while and there is no resume, even when using aria2 to download (maybe that's why it is not available in SourceForge?).

So this issue is just to let you know that the latest Gnome version is not available to download. I know it is a rolling release, but as the project is kinda new, probably there were important changes in the ISO for the latest version.

Regards

Update: today I tried to download from mirror.cachyos.org and it worked, maybe there was some connection problem or limitation due to the size of file. Anyway, the file is still missing in the official repo: sourceforge.net.

**Comment by ptr1337** [comment]
Hey @lfom 

Actually if you will use the online installation it does not really care which ISO you will use for the installation since you can choose at the installation process anyways your DE you want to choose. The different ISO's are mostly thought for the offline installation or the first look onto it.

I will have a look at the downloads, but we wanted anyways to release a new iso with some bug fixes and features (i.E bootloader selection at the online installation). 
You can choose between several mirrors to download, these have the exact same files on the server - just another location.
https://mirror.cachyos.org
https://build.cachyos.org
https://aur.cachyos.org
https://sg.cachyos.org
https://kr.cachyos.org

Feel free to join our discord or telegram for a bit faster support and some community talk. :)

Regards.

**Comment by lfom** [comment]
@ptr1337 Hi! Thanks you for your prompt response. Just another info: the Calamares installer does not start without an Internet connection, so it's not possible to do an offline installation. It happened with the 22.05 version on both KDE and Gnome. 

I saw you guys have a Telegram group too, I avoid using Discord as much as possible (Telegram too btw, I still use it mostly to follow channels, not yo chat anymore). I'd recommend using a fully FOSS alternative tho, like Matrix.

Thanks again! Regards.

**Comment by ptr1337** [comment]
> @ptr1337 Hi! Thanks you for your prompt response. Just another info: the Calamares installer does not start without an Internet connection, so it's not possible to do an offline installation. It happened with the 22.05 version on both KDE and Gnome.
> 
> I saw you guys have a Telegram group too, I avoid using Discord as much as possible (Telegram too btw, I still use it mostly to follow channels, not to chat anymore). I'd recommend using a fully FOSS alternative if possible tho, like Matrix.
> 
> Thanks again! Regards.

Hey! 
Yes this problem is currently known and should already fixed for the next release! 

We have also a matrix channel which is connected to the discord channels to have the community together. Its also Connected with the telegram group!

You can join via https://matrix.cachyos.org

**Comment by lfom** [comment]
I saw that a new version was released, and the Gnome version is available, so I am closing the issue. Thanks again!
