### ISSUE TITLE
Display fails to wake after sleep

### ISSUE THREAD

**Issue by xstefen** [CachyOS/CachyOS-Live-ISO#9]
Context: Gnome, KDE, and CLI live ISOs using NVIDIA option if present...afk long enough for sleep mode to initiate

Behavior: Shake mouse and press keys, everything wakes up except display, have to hard power cycle PC and start over

Expected: Everything wakes up including display

Device: Desktop, i7-7700k, 32gb RAM, NVIDIA GTX 1080 outputting via DVI

**Comment by ptr1337** [comment]
> 

Sorry for the delay, I have missed it.
Is this actually just happening with the ISO, right ? Or also after a installation?

Is this issue solved after the installation?

**Comment by xstefen** [comment]
Correct, only present on live iso

**Comment by ptr1337** [comment]
> Correct, only present on live iso

Actually I have tried to reproduce this issue in qemu with the new ISO, but seems not to happening so far.
I will have a look how its going with the new ISO when im going without qemu later!

Since you have a nvidia card, I could (maybe) imagine that this was a issue, through the nvidia driver boot option has been removed, but we have readded it once again.
I will let you know
